
// module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  module.exports = {
    docs: [
      {
        type: "doc",
        id: "intro",
      },
      {
        type: "category",
        label: "Error & Solution Log",
        items: [
          "debug-crontab-tasks",
          "fix-docusaurus-solutions",
        ],
      },
      {
        type: "category",
        label: "Learning GoLang",
        items: [
          "variables-in-golang",
          "arrays-in-golang",
        ],
      },
      {
        type: "category",
        label: "Learning Algorithms & Data Structure",
        items: [
          "uninformed-search",
        ],
      },
    ],
  };