
// module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  module.exports = {
    docs: [
      {
        type: "doc",
        id: "intro",
      },
      {
        type: "category",
        label: "Solutions to Bugs from Day to Day Activities",
        items: [
          "debug-crontab-tasks",
          "fix-docusaurus-solutions",
          "converting-images-to-webp",
          "setting-up-ghost-blog-on-linode",
        ],
      },
      {
        type: "category",
        label: "Learning GoLang",
        items: [
          "variables-in-golang",
          "arrays-in-golang",
        ],
      },
    ],
  };